# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
target 'TTHorizontalMenu' do
    # Uncomment this line if you're using Swift or would like to use dynamic frameworks
    # Pods for TTHorizontalMenu
    pod 'Masonry'
    pod 'SDWebImage'
    use_frameworks!
# pod 'ReactiveCocoa'
end
